# Generated by Django 5.0.6 on 2024-06-11 12:50

import apps.account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.account.models.CustomUserManager()),
            ],
        ),
    ]
